### PR TITLE
(feat) use pure lua(jit) crc algorithm

### PR DESCRIPTION
**Pull request by vinayakhulawale**
Use pure Lua module for crc
Add tests and rockspec

### CODE REVIEW

**Comment by vinayakhulawale** [comment]
@steve0511 - do you see any issues with this PR ?

**Comment by steve0511** [comment]
Sorry to be late, I see this MR is to replace FFI with pure lua for CRC. Did you have load test report compare?

**Comment by vinayakhulawale** [comment]
@steve0511 - will update this PR with report in couple of days.

**Comment by vinayakhulawale** [comment]
sorry this is taking time, lil busy in other projects ... will update PR soon with comparison report.

**Comment by vinayakhulawale** [comment]
@toredash - thanks for perf comparison and sorry I forgot to comeback and update this PR. We are using this internally in my company w/o any issues so far.  Let me rebase it so it's mergeable again.

**Comment by vinayakhulawale** [comment]
All tests are passing 
```
docker run -d --rm  -e "IP=0.0.0.0" -p 7000-7006:7000-7006 grokzen/redis-cluster:latest && sleep 10 && make test
1e2c0ed3a8b630a43bdc4fa6430123f1686a6e173e4c0e58274c9f3dda0ddda8
PATH=/Users/*****/nginx/sbin:$PATH prove -I../test-nginx/lib -r t
t/sanity.t .. ok
All tests successful.
Files=1, Tests=78, 12 wallclock secs ( 0.03 usr  0.01 sys +  0.47 cusr  0.64 csys =  1.15 CPU)
Result: PASS
```

**Comment by vinayakhulawale** [comment]
@steve0511 @toredash - this PR is ready for review again. Apart from using lua CRC, this PR includes following

-  make sure `flushall` and `flushdb` get's executed on all `master` nodes. 
-  return error if `shutdown` and `config` command are issued

`shutdown` and `config` command should be executed with care but i am OK to remove this logic or make rejection configurable with default being those get rejected.

**Comment by steve0511** [comment]
Hi, thanks for the MR.

Could we split the MR into two pieces?  1. using lua CRC  2. master nodes cmd and other.
Let's have them review one by one.

**Comment by vinayakhulawale** [comment]
@steve0511 - kept CRC related changed in this PR

**Comment by steve0511** [comment]
Thanks!

**Pull request merged**
