### PR TITLE
feat: add max_connection_timeout configuration parameter

### LINKED ISSUE #84: Long connection timeouts to redis cluster
Hi @steve0511,

First thank you for your useful redis client that supports redis cluster, it helps us a lot.

I am experiencing unwanted behavior when connecting to Redis using this client in edge cases such as when the cluster is down. In such cases I would like to timeout the operation and throw an error, if for example my redis cluster has 6 nodes and the connection timeout is 1000ms and the connection attempts is 2, i would expect it to timeout after 2-3 seconds and throw the error. However, as stated the cluster is 6 nodes meaning that using this client, the above case will multiply by 6(nodes)*2(connection attempts)¸ at the best case and in some cases I saw that with 6 nodes and the above configuration there were 14 timeout errors of connections to the redis cluster, each taking ~1second, and a few host is unreachable errors, leading to the whole operation to take 20seconds+
See this example log:
```
msg:2021/06/21 16:06:24 [error] 61#0: *27289 [lua] rediscluster.lua:218: fetch_slots(): failed to fetch slots: timeout;timeout;timeout;timeout;timeout;timeout;timeout;timeout;timeout;timeout;host is unreachable;host is unreachable;timeout;timeout;timeout;timeout;host is unreachable;host is unreachable, client: 127.0.0.1, server: kong, request: "GET /mickeys-receiver/health HTTP/1.1", host: "mickey.co"
```

To solve this, I suggest adding a general (optional) configuration param called `max_connection_timeout` which will timeout the `try_hosts_slots` function after the configured amount (if exists), which will allow us to be more in control when we have latency or connection problems from our Redis cluster.

Would love to hear your thoughts about this. I have a PR ready for this, since we need this functionality in our deployment.

PR - https://github.com/steve0511/resty-redis-cluster/pull/85

### PR DESCRIPTION
**Pull request by NivLipetz**
closes #84 

incase we want to be in control of how long it takes us to connect to a redis cluster, we should be able to control the timeout time, this PR includes this functionality.

This is the error message that is logged when a timeout happens:
```
msg:2021/06/21 20:20:40 [error] 50#0: *9280 [lua] rediscluster.lua:124: try_hosts_slots(): max_connection_timeout of 10000ms reached., client: 127.0.0.1, server: kong, request: "GET /mickey/health HTTP/1.1", host: "mickey.co"
```

### CODE REVIEW

**Review by shyimo — COMMENTED** [review]
Hi @NivLipetz. The PR looks good.
we also use this client and need this feature !
did you test it locally under load ?

**Comment by NivLipetz** [comment]
> Hi @NivLipetz. The PR looks good.
> we also use this client and need this feature !
> did you test it locally under load ?

Thanks @shyimo , we tested this under load with 1000RPS and it acts as expected, instead of taking 20+seconds for each request, the requests timeout after 10-12seconds with the 10second `max_connection_timeout` configuration

**Comment by steve0511** [comment]
LGTM, thanks for contributing.

**Comment by NivLipetz** [comment]
Happy to contribute 🙂 

@steve0511 do you have any estimations as to when you will release this to luarocks? We would like to install this pkg with the fix for our deployments. Thx again!

**Comment by steve0511** [comment]
@NivLipetz updated luarocks.

**Pull request merged**
